version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - lowerthirdnetwork
    ports:
      - "${WS_SERVER_PORT}:5000"
      - "${EXPRESS_SERVER_PORT}:3000"
    env_file:
      - .env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "5001:80" # Map port 5001 from host to port 80 in the container
    networks:
      - lowerthirdnetwork
    env_file:
      - .env

networks:
  lowerthirdnetwork:
